import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Layout from "../components/layout";
import styles from "../styles/Home.module.scss";

export default function Home() {
  return (
    <Layout>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>
            Read{" "}
            <Link href="/hello">
              <a>this page!</a>
            </Link>
          </h1>

          <p className={styles.description}>
            Get started by editing{" "}
            <code className={styles.code}>pages/index.js</code>
          </p>

          <div className={styles.grid}>
            <Link href="/cars/lambo">
              <a className={styles.card}>
                <h2>Lamborghini &rarr;</h2>
                <p>Find in-depth information Lambo</p>
              </a>
            </Link>

            <Link href="/cars/ferrari">
              <a className={styles.card}>
                <h2>Ferrari &rarr;</h2>
                <p>Find in-depth information Ferrari</p>
              </a>
            </Link>

            <Link href="/cars/tesla">
              <a className={styles.card}>
                <h2>Tesla &rarr;</h2>
                <p>Find in-depth information Tesla</p>
              </a>
            </Link>

            <Link href="/hello">
              <a className={styles.card}>
                <h2>Hello.js &rarr;</h2>
                <p>
                  Find in-depth information about <code>hello.js</code>
                </p>
              </a>
            </Link>
          </div>
        </main>

        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{" "}
            <span className={styles.logo}>
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                width={72}
                height={16}
              />
            </span>
          </a>
        </footer>
      </div>
    </Layout>
  );
}
